---
- hosts: sparkSlaves
  vars:
    - spark_version: v1.3.0
    - spark_binary: spark-1.3.0-bin-hadoop2.4.tgz
    - compile_spark: false
    - spark_defaults_conf: {}
    - spark_env_sh: {}
  roles:
    - ansible-role-java
    - groover.maven
    - ansible-role-spark
